services:
  message-broker-rabbitmq:
    container_name: message-broker-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/rabbitmq

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp" # Traces UDP
      - "14268:14268" # Traces HTTP
      - "4317:4317" # Open telemetry - gRPC
      - "4318:4318" # Open telemetry - HTTP

  # kong-database:
  #   image: postgres:13
  #   container_name: kong-database
  #   environment:
  #     POSTGRES_USER: kong
  #     POSTGRES_DB: kong
  #     POSTGRES_PASSWORD: kong
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - kong_data:/var/lib/postgresql/data

  # kong-migrations:
  #   image: kong:3.9
  #   command: kong migrations bootstrap
  #   depends_on:
  #     - kong-database
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: kong-database
  #     KONG_PG_USER: kong
  #     KONG_PG_PASSWORD: kong
  #     KONG_PG_DATABASE: kong

  api-gateway:
    image: kong:3.9
    container_name: api-gateway
    # depends_on:
    #   - kong-database
    environment:
      KONG_DATABASE: off
      # KONG_PG_HOST: kong-database
      # KONG_PG_USER: kong
      # KONG_PG_PASSWORD: kong
      # KONG_PG_DATABASE: kong
      # KONG_PROXY_ACCESS_LOG: /dev/stdout
      # KONG_ADMIN_ACCESS_LOG: /dev/stdout
      # KONG_PROXY_ERROR_LOG: /dev/stderr
      # KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000" # Proxy
      - "8001:8001" # Admin API
      - "8002:8002" # Admin UI
      - "8443:8443" # Proxy SSL
      - "8444:8444" # Admin API SSL

volumes:
  rabbitmq_data:
  # kong_data:
