services:
  invoices-pg:
    container_name: app-invoices
    image: bitnami/postgresql:17.2.0
    ports:
      - '5483:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d