services:
  pg:
    image: bitnami/postgresql:17.2.0
    ports:
      - '5482:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=orders
    volumes:
      - ./docker:/docker-entrypoint-initdb.d