_format_version: '3.0'
_transform: true

services:
  - name: orders
    url: http://host.docker.internal:3333
    protocol: http
    host: host.docker.internal
    port: 3333
    path: '/orders'

plugins:
  - name: cors
    config:
      origins:
        - '*'
      methods: 
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Authorization


